# Site settings
title: Simply Logical
subtitle: Intelligent Reasoning by Example
email: Peter.Flach@bristol.ac.uk
website: http://www.cs.bris.ac.uk/~flach
swish: "https://swish.simply-logical.space/"
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://labs.simply-logical.space" # the base hostname & protocol for your site
repo: "https://github.com/COMS30106/labs"
author: Peter Flach
# twitter_username: jekyllrb
# github_username:  jekyll
style: "simple"

# location of Prolog scripts
prolog: "prolog_scripts/"

# Build settings
markdown: kramdown

# Online folder location of Prolog scripts
onlinefolder: "https://raw.githubusercontent.com/COMS30106/prolog_scripts/7167c1fc5c259425d375c1ad1cfebef64d13cba1/"
