# Site settings
title: Simply Logical
subtitle: Intelligent Reasoning by Example
email: Peter.Flach@bristol.ac.uk
website: http://www.cs.bris.ac.uk/~flach
swish: "http://swish.simply-logical.space/"
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://labs.simply-logical.space" # the base hostname & protocol for your site
repo: "https://github.com/COMS30106/labs"
author: Peter Flach
# twitter_username: jekyllrb
# github_username:  jekyll
style: "simple"

# Build settings
markdown: kramdown
